spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

logging:
  level:
    fr.kryptonn.nexus: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG