spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    fr.kryptonn.nexus.axon: DEBUG
    org.hibernate: DEBUG
