server:
  port: 9000

spring:
  config:
    activate:
      on-profile: local

  mail:
    # GMAIL
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.debug: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

app:
  redis:
    enabled: true

logging:
  level:
    fr.kryptonn.nexus.axon: DEBUG
    org.hibernate: INFO  # Moins verbeux
    org.hibernate.SQL: DEBUG  # Garde juste les requêtes SQL
    org.hibernate.orm.jdbc.bind: TRACE  # Paramètres des requêtes